# Generated by Django 6.0.2 on 2026-05-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_message_file_message_file_name_message_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
    ]
